# Generated by Django 4.0.5 on 2022-06-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_product_liked'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, to='pages.product'),
        ),
    ]
