# Generated by Django 4.0.5 on 2022-06-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='liked',
        ),
    ]
