# Generated by Django 4.0.5 on 2022-06-21 09:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('telefon', 'Telefon'), ('noutbuk', 'Noutbuk'), ('mashina', 'Mashina'), ('hayvon', 'Hayvon'), ('uy', 'Uy'), ('mebel', 'Mebel')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('picture', models.ImageField(default='default.png', upload_to='')),
                ('price', models.PositiveIntegerField()),
                ('adress', models.CharField(choices=[('Toshkent', (('chilonzor', 'Chilonzor'), ('mirobod', 'Mirobod'), ('olmazor', 'Olmazor'), ('yunusobod', 'Yunusobod'), ('sergeli', 'Sergeli'), ('uchtepa', 'Uchtepa'))), ('Fargona', (('dangara', 'Dangara'), ('qoqon', 'Qoqon'), ('margilon', 'Margilon'), ('rishton', 'Rishton'), ('quva', 'Quva'), ('oltiariq', 'Oltiariq'))), ('Andijon', (('asaka', 'Asaka'), ('baliqchi', 'Baliqchi'), ('paxtaobod', 'Paxtaobod'), ('shaxrixon', 'Shaxrixon'), ('boston', 'Boston'), ('marhamat', 'Marhamat'))), ('Samarqand', (('jomboy', 'Jomboy'), ('urgut', 'Urgut'), ('qoshrabot', 'Qoshrabot'), ('kattaqorgon', 'Kattaqorgon'), ('oqdaryo', 'Oqdaryo'), ('payariq', 'Payariq'))), ('Buxoro', (('kogon', 'Kogon'), ('gijduvon', 'Gijduvon'), ('qorovulbozor', 'Qorovulbozor'), ('gazli', 'Gazli'), ('jondor', 'Jondor'), ('olot', 'Olot'))), ('Xorazm', (('xiva', 'Xiva'), ('gurlan', 'Gurlan'), ('urganch', 'Urganch'), ('xonqa', 'Xonqa'), ('shovot', 'Shovot'), ('bogot', 'Bogot')))], max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('liked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category')),
            ],
        ),
    ]
