# Generated by Django 4.0.5 on 2022-06-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Telefonlar', 'Telefon'), ('Noutbuklar', 'Noutbuk'), ('Mashinalar', 'Mashina'), ('Hayvonlar', 'Hayvon'), ('Uylar', 'Uy'), ('Mebellar', 'Mebel')], max_length=60),
        ),
    ]
