# Generated by Django 4.0.5 on 2022-06-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adress',
            field=models.CharField(blank=True, choices=[('Toshkent', (('chilonzor', 'Chilonzor'), ('mirobod', 'Mirobod'), ('olmazor', 'Olmazor'), ('yunusobod', 'Yunusobod'), ('sergeli', 'Sergeli'), ('uchtepa', 'Uchtepa'))), ('Fargona', (('dangara', 'Dangara'), ('qoqon', 'Qoqon'), ('margilon', 'Margilon'), ('rishton', 'Rishton'), ('quva', 'Quva'), ('oltiariq', 'Oltiariq'))), ('Andijon', (('asaka', 'Asaka'), ('baliqchi', 'Baliqchi'), ('paxtaobod', 'Paxtaobod'), ('shaxrixon', 'Shaxrixon'), ('boston', 'Boston'), ('marhamat', 'Marhamat'))), ('Samarqand', (('jomboy', 'Jomboy'), ('urgut', 'Urgut'), ('qoshrabot', 'Qoshrabot'), ('kattaqorgon', 'Kattaqorgon'), ('oqdaryo', 'Oqdaryo'), ('payariq', 'Payariq'))), ('Buxoro', (('kogon', 'Kogon'), ('gijduvon', 'Gijduvon'), ('qorovulbozor', 'Qorovulbozor'), ('gazli', 'Gazli'), ('jondor', 'Jondor'), ('olot', 'Olot'))), ('Xorazm', (('xiva', 'Xiva'), ('gurlan', 'Gurlan'), ('urganch', 'Urganch'), ('xonqa', 'Xonqa'), ('shovot', 'Shovot'), ('bogot', 'Bogot')))], max_length=60, null=True),
        ),
    ]
