# Generated by Django 4.0.5 on 2022-06-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='liked',
        ),
    ]
